### ISSUE TITLE
Paginate oc_coci_meta() or warn when there are too many DOIs?

### ISSUE THREAD

**Issue by LukasWallrich** [ropensci/citecorp#9]
Thanks for this great package!

I am trying to scrape and augment the citations of a bunch of articles - so I am obtaining them with `oc_coci_cites` and then passing the result into `oc_coci_meta`. However, with more than about 120 citations, then fails after quite a long time with `Request Header Fields Too Large (HTTP 431)`

Maybe `oc_coci_meta` could split the request automatically when too many DOI are requested? Or alternatively, just issue an explicit warning when there are more than say 100? As it stands, it took me rather long too figure out what the problem was (even though the error is already rather suggestive in hindsight.)

**Comment by LukasWallrich** [comment]
(Actually, I checked again and the number that works in one request might well be above 100, but definitely below 300)

**Comment by sckott** [comment]
@Selbosh is the new maintainer 😸
